set(CMAKE_FIND_FRAMEWORK_save ${CMAKE_FIND_FRAMEWORK})
set(CMAKE_FIND_FRAMEWORK NEVER)

FIND_PATH(OPENALSOFT_INCLUDE_DIR al.h
    HINTS
    $ENV{OPENALSOFTDIR}
    PATH_SUFFIXES AL
    PATHS
)

FIND_LIBRARY(OPENALSOFT_LIBRARY
    NAMES openal OpenAL32
    HINTS
    $ENV{OPENALSOFTDIR}
    PATH_SUFFIXES lib libs
    PATHS
)

set(CMAKE_FIND_FRAMEWORK ${CMAKE_FIND_FRAMEWORK_save})

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenALSoft DEFAULT_MSG OPENALSOFT_LIBRARY
    OPENALSOFT_INCLUDE_DIR)
MARK_AS_ADVANCED(OPENALSOFT_LIBRARY OPENALSOFT_INCLUDE_DIR)